apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-03-06T20:29:47Z"
  generateName: bala-concourse-web-85bb76b6d6-
  labels:
    app: bala-concourse-web
    pod-template-hash: 85bb76b6d6
    release: bala-concourse
  name: bala-concourse-web-85bb76b6d6-hhw98
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: bala-concourse-web-85bb76b6d6
    uid: 38b80274-5fe9-11ea-b157-42010a80011d
  resourceVersion: "13582"
  selfLink: /api/v1/namespaces/default/pods/bala-concourse-web-85bb76b6d6-hhw98
  uid: 38bc3d04-5fe9-11ea-b157-42010a80011d
spec:
  containers:
  - args:
    - web
    env:
    - name: CONCOURSE_ENABLE_GLOBAL_RESOURCES
      value: "true"
    - name: CONCOURSE_SECRET_RETRY_ATTEMPTS
      value: "5"
    - name: CONCOURSE_SECRET_RETRY_INTERVAL
      value: 1s
    - name: CONCOURSE_LOG_LEVEL
      value: info
    - name: CONCOURSE_BIND_PORT
      value: "8080"
    - name: CONCOURSE_BIND_IP
      value: 0.0.0.0
    - name: CONCOURSE_ADD_LOCAL_USER
      valueFrom:
        secretKeyRef:
          key: local-users
          name: bala-concourse-web
    - name: CONCOURSE_DEBUG_BIND_IP
      value: 127.0.0.1
    - name: CONCOURSE_DEBUG_BIND_PORT
      value: "8079"
    - name: CONCOURSE_INTERCEPT_IDLE_TIMEOUT
      value: 0m
    - name: CONCOURSE_GLOBAL_RESOURCE_CHECK_TIMEOUT
      value: 1h
    - name: CONCOURSE_RESOURCE_CHECKING_INTERVAL
      value: 1m
    - name: CONCOURSE_RESOURCE_TYPE_CHECKING_INTERVAL
      value: 1m
    - name: CONCOURSE_CONTAINER_PLACEMENT_STRATEGY
      value: volume-locality
    - name: CONCOURSE_BAGGAGECLAIM_RESPONSE_HEADER_TIMEOUT
      value: 1m
    - name: CONCOURSE_BUILD_TRACKER_INTERVAL
      value: 10s
    - name: CONCOURSE_POSTGRES_HOST
      value: bala-concourse-postgresql
    - name: CONCOURSE_POSTGRES_USER
      value: concourse
    - name: CONCOURSE_POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: bala-concourse-postgresql
    - name: CONCOURSE_POSTGRES_DATABASE
      value: concourse
    - name: CONCOURSE_KUBERNETES_IN_CLUSTER
      value: "true"
    - name: CONCOURSE_KUBERNETES_NAMESPACE_PREFIX
      value: bala-concourse-
    - name: CONCOURSE_GC_INTERVAL
      value: 30s
    - name: CONCOURSE_GC_ONE_OFF_GRACE_PERIOD
      value: 5m
    - name: CONCOURSE_GC_MISSING_GRACE_PERIOD
      value: 5m
    - name: CONCOURSE_AUTH_DURATION
      value: 24h
    - name: CONCOURSE_SESSION_SIGNING_KEY
      value: /concourse-keys/session_signing_key
    - name: CONCOURSE_MAIN_TEAM_LOCAL_USER
      value: test
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: CONCOURSE_PEER_ADDRESS
      value: $(POD_IP)
    - name: CONCOURSE_TSA_LOG_LEVEL
      value: info
    - name: CONCOURSE_TSA_BIND_IP
      value: 0.0.0.0
    - name: CONCOURSE_TSA_BIND_PORT
      value: "2222"
    - name: CONCOURSE_TSA_DEBUG_BIND_IP
      value: 127.0.0.1
    - name: CONCOURSE_TSA_DEBUG_BIND_PORT
      value: "2221"
    - name: CONCOURSE_TSA_HOST_KEY
      value: /concourse-keys/host_key
    - name: CONCOURSE_TSA_AUTHORIZED_KEYS
      value: /concourse-keys/worker_key.pub
    - name: CONCOURSE_TSA_HEARTBEAT_INTERVAL
      value: 30s
    image: concourse/concourse:5.6.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /api/v1/info
        port: atc
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 3
    name: bala-concourse-web
    ports:
    - containerPort: 8080
      name: atc
      protocol: TCP
    - containerPort: 2222
      name: tsa
      protocol: TCP
    - containerPort: 8079
      name: atc-debug
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /api/v1/info
        port: atc
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /concourse-keys
      name: concourse-keys
      readOnly: true
    - mountPath: /concourse-auth
      name: auth-keys
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: bala-concourse-web-token-76h98
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-concourse-kube-clust-default-pool-e2aa9ae4-w9zh
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: bala-concourse-web
  serviceAccountName: bala-concourse-web
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: concourse-keys
    secret:
      defaultMode: 256
      items:
      - key: host-key
        path: host_key
      - key: session-signing-key
        path: session_signing_key
      - key: worker-key-pub
        path: worker_key.pub
      secretName: bala-concourse-web
  - name: auth-keys
    secret:
      defaultMode: 256
      secretName: bala-concourse-web
  - name: bala-concourse-web-token-76h98
    secret:
      defaultMode: 420
      secretName: bala-concourse-web-token-76h98
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-03-06T20:29:47Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-03-06T20:30:28Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-03-06T20:30:28Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-03-06T20:29:47Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://24da0037f5ddd70dbdb089cfca8ceda07a598b906673661e39e80b297930632a
    image: concourse/concourse:5.6.0
    imageID: docker-pullable://concourse/concourse@sha256:32ff2e4bf9b4840ae58eb63874d83a25b991db5015b5652b1dac02dd97280d0f
    lastState: {}
    name: bala-concourse-web
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-03-06T20:29:48Z"
  hostIP: 10.128.0.49
  phase: Running
  podIP: 10.48.2.5
  qosClass: Burstable
  startTime: "2020-03-06T20:29:47Z"
